### ISSUE TITLE
Add Decimal Type

### ISSUE THREAD

**Issue by camexapps** [besstiolle/orm-ms#103]
Hi guys,

Nice work as always, can you guys please add a Decimal type support for the OrmCAST class?

Thanks

**Comment by camexapps** [comment]
Sorry, I am an idiot, I should just use integer right? 

E.g using a 'size' of something like M.D 

M - total length
D - digits right of the decimal point

So, for example '4.2'

**Comment by besstiolle** [comment]
i don't remember having tested this case.

Could you confirm that it's works please (generation of the table, insert, select) ?

thank you

**Comment by besstiolle** [comment]
btw it's a pleasure to see it's used and is useful :)

**Comment by camexapps** [comment]
Yep it does work as expected

Thanks
