### ISSUE TITLE
CMS Made Simple v2: admin error in OrmSkeleton

### ISSUE THREAD

**Issue by airelibre** [besstiolle/orm-ms#107]
There is a problem with CMS Made Simple v2 (currently in beta)

In the file action.defaultadmin.php, the theme should be called with:

`$admintheme = cms_utils::get_theme_object();`

And after:
`$img_delete = $admintheme->DisplayImage('icons/system/delete.gif','delete','','','systemicon');
$img_edit = $admintheme->DisplayImage('icons/system/edit.gif','edit','','','systemicon');
$img_view = $admintheme->DisplayImage('icons/system/view.gif','view','','','systemicon');`

Otherwise, it will drop a Fatal error

**Comment by besstiolle** [comment]
oups.. i found another reference inside OrmSkeleton...
