### ISSUE TITLE
Error while upgrading Orm from 0.3.1 to 0.3.2 on a live instance

### ISSUE THREAD

**Issue by WebEP** [besstiolle/orm-ms#108]
Fatal error: Call to a member function GetPreference() on a non-object in /home/xxx/www/modules/Orm/lib/class.OrmTrace.php on line 153

**Comment by besstiolle** [comment]
I just tested again and everything worked like a charme ... have you more information ? (stack trace)

**Comment by besstiolle** [comment]
you can also try this modification : into lib/class.OrmTrace.php line 153

change 
```php if($orm->GetPreference('loglevel', OrmTrace::$INFO) > $level) {return;} ```
by 
```php if($orm != null && $orm->GetPreference('loglevel', OrmTrace::$INFO) > $level) {return;} ```

**Comment by besstiolle** [comment]
It should be fix in the 0.3.3-SNAPSHOT : https://github.com/besstiolle/orm-ms/commit/e31ee67b2ef574dd15d50ae2f547f071d6b65644
