### ISSUE TITLE
Entity Generator does not put dot before entity name in filename

### ISSUE THREAD

**Issue by nljos** [besstiolle/orm-ms#110]
While encouraged by your presentation at Geekmoot in Ghent, I tried your orm module for the very first time.
I used the entity generator. I found that the files are not saved with a dot before the name of the entity, which caused that install/uninstall did not work. After I put the dots manually in the filenames, all worked very well.. My first steps are set succesfully ;)

orm 0.3.2 / cmsms 1.11.10

**Comment by besstiolle** [comment]
Exactly. I've already fixed the bug for the next release. You can find it
on branch 3.x on github. I'll made the new release this week.

Thank you for the feedback !

**Comment by nljos** [comment]
Thanks, I just saw it in your changelog. Didn't saw it in the issues..

**Comment by besstiolle** [comment]
fixed in 0.3.3-SNAPSHOT : 1f4c930ce556f355c006ddd9537799a0303b47b

**Comment by besstiolle** [comment]
available in 0.3.3.
